language: cpp
compiler: 
  - gcc
  - clang
os: 
  - linux
  - osx
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y protobuf-compiler libprotobuf-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install protobuf; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install openssl; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew link openssl --force; fi
install:
  - cmake -DBUILD_TEST=on .
  - make -j 8
before_script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
  - echo $JAVA_HOME
  - git clone https://github.com/Kinetic/kinetic-java
  - mvn -f ./kinetic-java/pom.xml -DskipTests clean package
  - ./kinetic-java/bin/startSimulator.sh &
  - sleep 10
script: 
  - make check
  - make integration_test
